export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL'
export const UPLOAD_IMAGE_RESET = 'UPLOAD_IMAGE_RESET'

export const CREATE_CAROUSEL_REQUEST = 'CREATE_CAROUSEL_REQUEST'
export const CREATE_CAROUSEL_SUCCESS = 'CREATE_CAROUSEL_SUCCESS'
export const CREATE_CAROUSEL_FAIL = 'CREATE_CAROUSEL_FAIL'
export const CREATE_CAROUSEL_RESET = 'CREATE_CAROUSEL_RESET'

export const LIST_CAROUSEL_REQUEST = 'LIST_CAROUSEL_REQUEST'
export const LIST_CAROUSEL_SUCCESS = 'LIST_CAROUSEL_SUCCESS'
export const LIST_CAROUSEL_FAIL = 'LIST_CAROUSEL_FAIL'
export const LIST_CAROUSEL_RESET = 'LIST_CAROUSEL_RESET'

export const DELETE_CAROUSEL_REQUEST = 'DELETE_CAROUSEL_REQUEST'
export const DELETE_CAROUSEL_SUCCESS = 'DELETE_CAROUSEL_SUCCESS'
export const DELETE_CAROUSEL_FAIL = ' DELETE_CAROUSEL_FAIL'
export const DELETE_CAROUSEL_RESET = 'DELETE_CAROUSEL_RESET'
